#pragma once

namespace LibNet
{
	enum NET_ERROR
	{
		NONE = 0,

		INIT_FAIL_QUEUE_IS_NULL = 1,
		INIT_FAIL_SOCKET_CREATE = 2,
		INIT_FAIL_SOCKET_OPT = 3,
		INIT_FAIL_IOCP_HANDLE_NULL = 4,
		INIT_FAIL_IVALID_SOCKET = 5,
		INIT_FAIL_BIND = 6,
		INIT_FAIL_IOCP_REGISTER = 7,

		START_FAIL_NOT_INITED = 11,
		START_FAIL_LISTEN = 12,
		START_FAIL_WSAIoctl = 13,
		START_FAIL_SOCKET_CREATE = 14,

	};
}